- name: Configuring router
	hosts: CiscSDN
	gather_facts: yes
	tasks:

		- name: Set IP address for g1/0
			cisco.ios.ios_config:
				lines:
					- ip address 192.168.17.1 255.255.255.0
					- no shutdown
				parents: interface GigabitEthernet1/0
			register: result

		- name: Save the config
			cisco.ios.ios_config:
				lines:
				- write mem
		
 
